### ISSUE TITLE
Proposal to add ability to use a different brush for some edges

### ISSUE THREAD

**Issue by kmosegaard** [Oaz/AvaloniaGraphControl#12]
Hi.

I want to be able to color some edges in my graph differently. I've found that it's possible to change the color of all edges using Styles, but I haven't figured out how to color an edge separately. Please enlighten me, if you have the solution.

If not, I propose that we expand the Edge class to take a brush color and use that in the Connection class for setting the Brush property. I can submit a pull request if you think it's a good idea. Please say so if you think another approach is needed.

Regards, Kristian.

**Comment by Oaz** [comment]
Hi,

The Brush property on the Connection control can be bound in XAML.
I have just added a "Colored Edges" example to show what can be done in this area.
Actually, if I were to rewrite the Edge class today, I would remove the graphical stuff inherited from MSAGL (the head and tail symbols) and transform them into control properties.
The idea here is that the model classes, such as Edge, shall not embed any graphical stuff.

Hope this helps,

Olivier

**Comment by kmosegaard** [comment]
And that is exactly what I wanted, I just couldn't figure out the way, so thanks for the example that helped a lot. Your sentiment about leaving out graphical stuff from the Edge class is understandable.

I'll close this issue since there is not an issue anymore.

Regards, Kristian
