### ISSUE TITLE
How do I move nodes with the mouse?

### ISSUE THREAD

**Issue by Kibnet** [Oaz/AvaloniaGraphControl#5]

**Comment by Oaz** [comment]
Well... You can't.
That is not part of my plan. I want to automatically layout rich user controls. No need to move them for the user.

**Comment by Kibnet** [comment]
Sadly. And if I help you do that, would you mind? I would like to use your component to create a node editor.

**Comment by Oaz** [comment]
I'm afraid I cannot of any help on this one.
- I don't know how dragging controls works on Avalonia. This would take some dive into Avalonia docs.
- I don't know how to recompute the edges after some node is moved. Maybe MSAGL can do that but I'm not sure.
- I don't know how to handle the layout if some node is moved to a place where it intersects with another existing node. Here, again, this would imply some serious digging into MSAGL code.

**Comment by Kibnet** [comment]
I've seen that avalonia allows you to drag objects. So it is possible and we can see how it is done with them. You don't need to recalculate the graph yet, i just want to be able to drag nodes. And then make functions for creating and deleting nodes directly in the graph.

**Comment by Oaz** [comment]
The problem is that if you drag the nodes without recalculating the graph then the edges won't move.

**Comment by michaelkruglos** [comment]
The code relevant for dragging is most likely here: https://github.com/microsoft/automatic-graph-layout/blob/master/GraphLayout/Drawing/LayoutEditing/GeometryGraphEditor.cs#L163
